version: '3.0'
services:
  nginx:
    image: nginx
    volumes:
      - './:/var/www'
      - './docker/nginx:/etc/nginx/conf.d/'
    links:
      - php7.4-fpm
    ports:
      - "8081:80"
  php7.4-fpm:
    build: './docker/php7.4-fpm'
    volumes:
      - './:/var/www'
    ports:
      - '9000:9000'


